### ISSUE TITLE
train on a single node with 4 GPUs

### ISSUE THREAD

**Issue by ShiZiqiang** [nv-tlabs/CLD-SGM#4]
Thank you so much for open sourcing this awesome work. However, I want to know how to train on a single node with multiple GPUs, e.g. 4 GPUs, is the following cmd right? Thank you in advance.

CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py -cc configs/default_cifar10.txt -sc configs/specific_cifar10.txt --root ./ROOT --mode train --workdir work_dir/cifar10 --n_gpus_per_node 4 --training_batch_size 64 --testing_batch_size 64 --sampling_batch_size 64

**Comment by timudk** [comment]
Hi ShiZiqiang,

Yes, that's the right command. Note, however, that your training/testing batch size will be 256=4*64.

**Comment by ShiZiqiang** [comment]
> Hi ShiZiqiang,
> 
> Yes, that's the right command. Note, however, that your training/testing batch size will be 256=4*64.

Hi, Tim,

Thank you so much for the quick help.
